### ISSUE TITLE
Add copyright notice to macros/src/lib.rs

### ISSUE THREAD

**Issue by robertdfrench** [oxidecomputer/rusty-doors#1]
Hello!

I would like to steal the procedural macro definition you have for `#[door]`. Would you please add a copyright notice to https://github.com/oxidecomputer/rusty-doors/blob/main/macros/src/lib.rs ? I will then make sure the same notice is applied to my derivative of that file at https://github.com/robertdfrench/rusty-doors/blob/trunk/macros/src/lib.rs

**Comment by rcgoodfellow** [comment]
Sure thing!

**Comment by robertdfrench** [comment]
Thank you!
